<a href="https://colab.research.google.com/github/daladuli-vivek/Advanced-Programming-Practice/blob/main/__01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


Introduction to Tensor

Creating tensor


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([69,69])
vector

tensor([69, 69])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[8,9],
                      [14,15]])
MATRIX

tensor([[ 8,  9],
        [14, 15]])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX.ndim

2

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[[3,2,3],
                        [3,4,5],
                        [5,6,7],
                        [3,6,7]]]])
TENSOR

tensor([[[[3, 2, 3],
          [3, 4, 5],
          [5, 6, 7],
          [3, 6, 7]]]])

In [ ]:
TENSOR.shape

torch.Size([1, 1, 4, 3])

In [ ]:
TENSOR.ndim

4

##Random Tensors
###why Random Tensors?
The Neural networks start with randon tensors and adjust those random numbers
to represent the data
######RESOURCE:https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
#Create Random tensor
rand_tensor = torch.rand(2,3)
rand_tensor

tensor([[0.7523, 0.1200, 0.0589],
        [0.8079, 0.8886, 0.0903]])

In [ ]:
rand_tensor.shape

torch.Size([2, 3])

In [ ]:
rand_tensor.ndim

2

In [ ]:
#Create a random tensor with an image tensor
Rand_image_size_tensor=torch.rand(size=(224,224,3)) # HEIGHT, WIDTH, COLOURS(RGB)
Rand_image_size_tensor.shape, Rand_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
#ZEROS and ONES Tensor
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(4,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

###Creating a Range of tensors

In [ ]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_thousand = torch.arange(start=1, end=1000, step=69)
one_to_thousand

tensor([  1,  70, 139, 208, 277, 346, 415, 484, 553, 622, 691, 760, 829, 898,
        967])

In [ ]:
#creating tensors like
ten_zeros = torch.zeros_like(input = one_to_thousand)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

####Tensor Datatypes
NOTE: Tensor datatypes is one of the 3 big errors in the pytorch and deep learning

1. Tensors not the right datatype
2. Tensors not the right shape
3. Tensors not on the right device


In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #What datatype is the tensor(e.g. float 32 or float 16)
                               device=None, #What device is your tensor on
                               requires_grad=False)#whether or not track gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor #Converted the 32 float type tensor into 16 float type tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
some_tensor = torch.rand(4,3)
some_tensor

tensor([[0.5110, 0.3870, 0.1485],
        [0.2352, 0.2324, 0.7543],
        [0.7348, 0.0721, 0.5025],
        [0.2858, 0.0478, 0.4883]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Device of the tensor: {some_tensor.device}")

tensor([[0.5110, 0.3870, 0.1485],
        [0.2352, 0.2324, 0.7543],
        [0.7348, 0.0721, 0.5025],
        [0.2858, 0.0478, 0.4883]])
Datatype of tensor: torch.float32
Shape of the tensor: torch.Size([4, 3])
Device of the tensor: cpu


###Manipulating Tensors

In [ ]:
tensor = torch.tensor([3,2,1])
tensor

tensor([3, 2, 1])

In [ ]:
tensor+10 #addition of tensor

tensor([13, 12, 11])

In [ ]:
torch.add(tensor, 10) # another way to add numbers

tensor([13, 12, 11])

In [ ]:
tensor-1 #subtraction of tensor

tensor([2, 1, 0])

In [ ]:
tensor*10 #Multiplication of tensor (element wise)

tensor([30, 20, 10])

## Matrix multplication 

###Two main ways of performing multiplication in neural network and deep learning
####1. Element wise multiplication
####2. Matrix Multiplication(dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The inner dimensions must match:
   ' (3,2) @ (3,2) ' wom't work {'@' this symbol of matrix multiplication}
   '(2,3) @ (3,2)' this will work
2. The resulting matrix has the shape of the outer dimension
   ' (2,3) @ (3,2) ' -> (3,3) 


In [ ]:
#Element wise multiplication
print(tensor , "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([3, 2, 1]) * tensor([3, 2, 1])
Equals: tensor([9, 4, 1])


In [ ]:
#Matrix multiplication
%%time #shows the calculation time
torch.matmul(tensor,tensor)

CPU times: user 1.22 ms, sys: 13 µs, total: 1.24 ms
Wall time: 3.61 ms


tensor(14)

In [ ]:
tensor_A = torch.tensor([[3,2],
             [4,3],
             [6,9]])
tensor_A.shape

torch.Size([3, 2])

To fix our tensor shape issues, we manipulate the shape ot the tensor using a "transpose"

In [ ]:
tensor_A.T, tensor_A.T.shape

(tensor([[3, 4, 6],
         [2, 3, 9]]),
 torch.Size([2, 3]))

Finding the min, max, mean, sum, etc(tensor aggregation)

In [ ]:
A = torch.arange(0,50,5) #Create a tensor
A

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
#Find min
torch.min(A), #or
A.min()

tensor(0)

In [ ]:
#Find the max
torch.max(A) #or
A.max()

tensor(45)

In [ ]:
#Find the mean - NOTE: the torch.mean()function requires a tensor of float32 datatype
torch.mean(A.type(torch.float32)) #or
A.type(torch.float32).mean()

tensor(22.5000)

Finding the positional min and max

In [ ]:
A

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
#Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the min value occurs
A.argmin() 

tensor(0)

In [ ]:
A[0]

tensor(0)

In [ ]:
#Find the position in tensor that has the max value with argmax()
A.argmax()

tensor(9)

In [ ]:
A[9]

tensor(45)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to defined shape
* View- Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
*Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
#Create a tensor
import torch
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
#Add extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
#change the view
z = x.view(1,9)
z,z.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
#changing z changes x (because a view of tensor shares the same memory as the orginial input)
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
#stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
#troch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New Tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New Shape: torch.Size([9])


In [ ]:
x_reshaped.squeeze()

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#torch.permute- rearranges the dimensions of a target tensor in specified order
x_original = torch.rand(size=(224,224,3)) #height, width, colour
#permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1)# shift axis 0->1, 1->2, 2->0

print(f"Previous shape = {x_original.shape}")
print(f"New shape = {x_permuted.shape}")# colour,height,width

Previous shape = torch.Size([224, 224, 3])
New shape = torch.Size([3, 224, 224])


In [6]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [7]:
#Index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
#index on the middle bracket(dim=1)
x[0][0]

tensor([1, 2, 3])

In [12]:
#index on the last bracket(last dim)
x[0][2][2]

tensor(9)

In [13]:
x[:,:,2]

tensor([[3, 6, 9]])

###Pytorch tensors and Numpy

Numpy is popular scientific python numerical computing library
and because of this, pytorch has functionality to interact with it.

       * Data in numpy,want in pytorch tensor ->torch.from_numpy(ndarray)
       * pytorch tensor -> numpy -> torch.Tensor.numpy()

In [18]:
#Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)#{.type(torch.float32)} Note: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float 64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [20]:
tensor.dtype

torch.float32

In [21]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [22]:
tensor = tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility(trying to make random out of random):
 
 How Neural network learns:
 start with a random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> again->....

 To reduce the randomness in neural networks and pytorch comes the concept of a 'Random seed'.
 Essentially what the random seed does is'flavour' the randomness

In [24]:
import torch
#create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A != random_tensor_B)

tensor([[0.3981, 0.6530, 0.7394, 0.6615],
        [0.1140, 0.5291, 0.7214, 0.8699],
        [0.8984, 0.3812, 0.3501, 0.1234]])
tensor([[0.4385, 0.4010, 0.1940, 0.9158],
        [0.3102, 0.7107, 0.3695, 0.1487],
        [0.4365, 0.5383, 0.3672, 0.6745]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
